name: Build and Deploy Static Content to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build the site
        run: |
          function retry {
            local n=1 max=5 delay=2
            while true; do
              "$@" && break || {
                ((n++)) || true
                echo "Attempt $n"
                sleep $delay
              }
              ((n>max)) && return 1
            done
          }
          retry npm run predeploy
        env:
          NODE_ENV: production
          REACT_APP_GA_TRACKING_ID: UA-68649021-1

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-22.04

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: https://sagarsave10.github.io

    steps:
      - name: Download built artifact
        uses: actions/download-pages-artifact@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
